### ISSUE TITLE
Add boilerplate code for React project

### ISSUE THREAD

**Issue by warrenferns** [githubcrce/PasswordGenerator#1]
This issue should resolve the following:
1. Adds package.json
2. Adds App.js, App.css, index.js, index.css

**Comment by akadeepesh** [comment]
Let me do this, assign me please

**Comment by akadeepesh** [comment]
Made a PR

**Comment by Durgeshsejekar** [comment]
I wnt to work on this issue so please can u assign me.

**Comment by Irfan7014** [comment]
Assign to me @warrenferns please

**Comment by Irfan7014** [comment]
Pull request created @warrenferns
